name: neom_commerce
description: Commerce Details for Cyberneom.
version: 1.1.0
homepage: https://github.com/emmanuel-montoya/neom_commerce
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commons:
    git:
      url: https://github.com/Cyberneom/neom_commons.git
  neom_posts:
    git:
      url: https://github.com/Cyberneom/neom_posts.git

  #not working for products
#  woosignal: ^3.8.0
  in_app_purchase: ^3.1.7
  in_app_purchase_storekit: ^0.3.6+4
  just_audio: 0.9.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  neom_commons:
    path: ../neom_commons
  neom_posts:
    path: ../neom_posts
  intl: 0.18.1

# The following section is specific to Flutter packages.
flutter:
